#!/usr/bin/env bash

echo "WAIT FOR TERMINAL INITIALIZATION"
sleep 1
clear

function print_blank {
	if [[ $# -lt 1 ]]; then
		echo 'You need to provide width in characters!'
		exit 1
	fi

	printf " %.0s" $(seq 1 $1)
}

function print_separator {
	#local DATE=$(date +%H:%M)
	local DATE=$(pwd)
	local HALF_WIDTH=$(( ($(tput cols) - ${#DATE}) / 2 ))
	local RESULT="$(print_blank $HALF_WIDTH)$DATE$(print_blank $HALF_WIDTH)"

	if [[ ${#RESULT} -lt $(tput cols) ]]; then
		echo "$RESULT "
	else
		echo "$RESULT"
	fi
}

PS1='\[\033[7;35m\]$(print_separator)\[\033[0;35m\]● \[\033[0m\]'
PS0='\[\033[0m\]'
PATH=$HOME/.nimble/bin:$HOME/.local/bin:$PATH
DOTNET_SYSTEM_NET_DISABLEIPV6=1
source ~/.config/secret_env
